### DISCUSSION TITLE
How to handle `host_taxid` metadata information.

### DISCUSSION THREAD

**Discussion by mslarae13** [microbiomedata/issues#838] [General]
It was recently discovered from looking at the EcoFab data that host_taxid has no pattern constrain and is a sting and apparently caused some failures as the submitter formatted the metadata field to look like how NCBI displays the metadata (example "NCBI:txid2821538")

In short, the `host_taxid` slot in `nmdc-schema` requires a curie. In NMDC-submission portal the users provide the ID as it's written by [NCBI](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=2821538&lvl=3&lin=f&keep=1&srchmode=1&unlock). 

`nmdc-schema` doesn't recognize NCBI as a valid pre-fix & it's been pointed out that writting the host_taxid as "NCBI:txid2821538" isn't a valid ID/curie structure.

To decide
- Since NCBI:txid is not a valid curie, what's the better way to structure this for MongoDB.
- Using just the #s, and assume the prefix means the data is stored differently than it's provided to the user
- Can mongo / nmdc-schema have a different structure than the NMDC submission-schema to allow the user to submit the ID as they see it, with ingest script checking and fixing.
- GSC allows a string for this term. But we can manipuate the term. `host_taxid` will become MIxS modified

Please add your thoughts on how we should proceed and what we can do.

As a note, definitely as a LATER goal, the submission portal should validate these IDs via an API or some check with NCBI. But, this is not a small task & isn't feasible if we need a NOW resolution.

**Comment by sierra-moxon** [comment]
related issues: 
https://github.com/obophenotype/ncbitaxon/issues/40
https://github.com/biopragmatics/bioregistry/issues/1044
https://github.com/biopragmatics/bioregistry/issues/1104

**Comment by turbomam** [comment]
NCBI stores `host_taxid` values as strings, but the vast majority of those unqique values can be cast directly to integers.

Here's some highlights from our BBOP/NMDC Biosamples in PostgreSQL database:

```sql
select
	value,
	count(1)
from
	ncbi_attributes_all_long naal
where
	harmonized_name = 'host_taxid'
group by
	value
having
	count(1) > 1000
order by
	count(1) desc
;
```

<details>
  <summary>Resuts</summary>

|value         |count  |
|--------------|------:|
|9606          |121,213|
|10090         |49,727 |
|9556          |14,371 |
|9913          |9,148  |
|not applicable|6,776  |
|4577          |4,890  |
|9031          |4,711  |
|3702          |4,651  |
|9825          |4,266  |
|3555          |3,511  |
|381124        |3,313  |
|9615          |3,273  |
|8030          |3,081  |
|57918         |2,608  |
|9940          |2,489  |
|10116         |2,142  |
|NA            |2,086  |
|410658        |1,929  |
|350892        |1,817  |
|13676         |1,423  |
|72873         |1,296  |
|2980491       |1,283  |
|9823          |1,261  |
|1256227       |1,246  |
|29159         |1,224  |
|10036         |1,207  |
|7175          |1,171  |
|[taxon:3702]  |1,157  |
|9544          |1,018  |


</details>

**Reply by aclum** [reply]
Everything here should be an int, ones that aren't are workarounds (not applicable) or b/c its written as a bracketed curie.

**Comment by turbomam** [comment]
Here is the GSC specification. (Thanks @mslarae13 )

https://genomicsstandardsconsortium.github.io/mixs/0000250/#linkml-source

```yaml
name: host_taxid
annotations:
  Expected_value:
    tag: Expected_value
    value: NCBI taxon identifier
description: NCBI taxon id of the host, e.g. 9606
title: host taxid
from_schema: https://w3id.org/mixs
keywords:
- host
- host.
- taxon
slot_uri: MIXS:0000250
alias: host_taxid
domain_of:
- Agriculture
- FoodFarmEnvironment
- HostAssociated
- PlantAssociated
- SymbiontAssociated
range: string
```

**Comment by turbomam** [comment]
You can see that this is one of the many MIxS slots for which I never really finished the LinkML conversion. Maybe because I wasn't sure about any of the same stuff we're discussing now!

Ideally we would remove the `annotations` and move the bit after `e.g. ` into `examples`. I interpret that example as meaning that integer values are intended (in line with the majority of the values in the database)

**Comment by turbomam** [comment]
Here's the nmdc-schema specification. In retrospect, it's semantics are quite different from GSC's

https://microbiomedata.github.io/nmdc-schema/host_taxid/#linkml-source

```yaml
name: host_taxid
annotations:
  expected_value:
    tag: expected_value
    value: NCBI taxon identifier
  occurrence:
    tag: occurrence
    value: '1'
description: NCBI taxon id of the host, e.g. 9606
title: host taxid
comments:
- Homo sapiens [NCBITaxon:9606] would be a reasonable has_raw_value
from_schema: https://w3id.org/nmdc/nmdc
aliases:
- host taxid
rank: 1000
is_a: core field
slot_uri: MIXS:0000250
alias: host_taxid
domain_of:
- Biosample
range: ControlledIdentifiedTermValue
multivalued: false
```
