### ISSUE TITLE
add explicit units when instantiating biosamples if unit was assumed in DH

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#236]
Here, the unit for `elev` was specified by the DH user, but not for `depth` probably because DH said something like "enter depth in meters, numerical par only")

```yaml
  depth:
    has_raw_value: '0.02'
    has_numeric_value: 0.02
  elev:
    has_raw_value: 1500 m
    has_unit: metre
    has_numeric_value: 1500.0
```
