### ISSUE TITLE
Update Study DOI to specify award doi and multivalued in NMDC schema

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#338]
Currently on the study landing page, the `doi` for `Study` is captured twice 1) as a an unclickable doi under study details and 2) as a citation under Dataset Citation. This link is the award doi and not a dataset citation. The text in the portal will need to be changed to "Award DOI" and will need to be changed to be multivalued.

I propose the following nmdc schema changes by editing the local `doi` slot for `Study`:

- [ ] so that the `description` specifies that this is an award doi (not a dataset citation for the study).
- [ ] Adding `aliases: award doi`
- [ ] and `multivalued: true`

@mslarae13 
@turbomam Does this make good sense? If so, I can add this to the schema.

**Comment by brynnz22** [comment]
@mslarae13 do you know if all the studies we currently capture and we will continue to capture are only award dois? Do we capture other kinds of dois (will there actually be dataset dois, for example?). If so, then we won't want to add `award doi` as a clarification. But if are only capturing award dois, then we can add it as a comment or annotation to the slot.

**Comment by brynnz22** [comment]
@turbomam adding sub_properties of `doi` sounds great to me. That allows room for flexibility with dois moving forward. If we want to/will capture different kinds of dois in the future.

For `on_hover`, I now you mentioned possibly using this for the `orcid` slot. I didn't create an issue for that because I was not quite sure how that would work yet. So it sounds like holding off on that until we review. 

Thanks for your feedback!

**Comment by aclum** [comment]
doi should have range of curie

**Comment by brynnz22** [comment]
@aclum after talking with @turbomam we wanted to check to make sure you do want to commit to make the range a curie. If so, we have to define what the prefix for doi is.

**Comment by turbomam** [comment]
This was the previous definition of `doi`:

```yaml
  doi:
    is_a: attribute
    range: AttributeValue
```

where the `AttributeValue` Class is

```yaml
  AttributeValue:
    description: >-
      The value for any value of a attribute for a sample. 
      This object can hold both the un-normalized atomic value and the structured value
    slots:
      - has_raw_value
      - was_generated_by
    slot_usage:
      type:
        description: >-
          An optional string that specified the type of object.
```

and the `attribute` type is

```yaml
  attribute:
    aliases: [ 'field', 'property', 'template field', 'key', 'characteristic' ]
    abstract: true
    description: >-
      A attribute of a biosample. Examples: depth, habitat, material.
      For NMDC, attributes SHOULD be mapped to terms within a MIxS template
```

The `doi` portion of legacy Studies look like this

```yaml
doi:
  has_raw_value: "https://doi.org/10.25585/1487763"
```

now we will have something more like 

```yaml
award_dois: "https://doi.org/10.25585/1487763"
```

where 

```yaml
  award_dois:
    is_a: dois
    description: >-
      One or more DOIs that links a study, or similar entiry, to information about the funding authority.
```

and

```yaml
  dois:
    # is_a: attribute
    todos:
      - the previous doi slot was an attribute, but attribute seems committed to biosamples
      - should we assert a parent term here?
    range: uriorcurie
    description: >-
      A digital object identifier, which is intended to persistantly identify some resource on the web.
    multivalued: true
    aliases:
      - DOIs
      - digital object identifiers
```

@aclum would you prefer that the data look like

```yaml
award_dois: "doi:10.25585/1487763"
```

where we define the expansion of the `doi` prefix as 'https://doi.org/'
