### ISSUE TITLE
Units in NMDC

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#552]
This is a super issue to gather all the existing issues about units in NMDC.
This includes what units we should require, in what format, and how they'll be enforced. As well as how units will be required or expressed in NMDC schema vs submission schema.

- [x] https://github.com/microbiomedata/nmdc-schema/issues/1257
- [x] https://github.com/microbiomedata/sample-annotator/issues/11
- [x] https://github.com/microbiomedata/submission-schema/issues/210
- [x] https://github.com/microbiomedata/submission-schema/issues/206
- [x] https://github.com/microbiomedata/nmdc-schema/issues/857
- [x] https://github.com/microbiomedata/metadata_converter/issues/9
- [x] https://github.com/microbiomedata/issues/issues/236
- [x] https://github.com/microbiomedata/DataHarmonizer/issues/122
- [x] https://github.com/microbiomedata/sample-annotator/issues/12

**Comment by mslarae13** [comment]
It was decided that NMDC would implement UCUM units.

**Comment by turbomam** [comment]
see also closed issue
- https://github.com/microbiomedata/issues/issues/612

**Comment by turbomam** [comment]
## What does it mean for NMDC to implement UCUM?

UCUM is essentially a specification for how units of measure should be written out

- https://en.wikipedia.org/wiki/Unified_Code_for_Units_of_Measure
- https://github.com/ucum-org/ucum

If NMDC implements/follows/adheres to UCUM, then all [units](https://microbiomedata.github.io/nmdc-schema/has_unit/) in [QuantityValue](https://microbiomedata.github.io/nmdc-schema/QuantityValue/) instances would be composed from the [UCUM list](https://github.com/ucum-org/ucum/tree/main/common-units)

That means somebody will be responsible for ensuring that non-UCUM units are absent from NMDC records. The schema can help with that to a large degree, but other human and computer resources will be required in some ways.

We can think of three groups of parties who have an interest in the costs and benefits of whatever implmentation we choose:
- NMDC as designers and implementers
- Data submitters
- Data users

There will be virtually no costs to Data Users, only benefit. If all measurements of the same type (in the same slot)  in NMDC data use the same unit or can easily be converted to the same unit, then finding similar (or deterministically different) Biosamples will become much easier.

**Comment by turbomam** [comment]
### Where will the UCUM-adherence be specified?
- submisson-schema ?
- nmdc-schema ?

**Comment by turbomam** [comment]
### Review of QuantityValue or non-class ranges in use by nmdc-schema

This list includes MIxS-defined as well as native nmdc-schema slots. As of 2025-03-27, the MIxS content comes from the old https://github.com/microbiomedata/mixs/commit/e72235c922e5f8671f66418b03a30807e4f10ac3, not https://github.com/GenomicsStandardsConsortium/mixs/tree/v6.2.0

- ~ 190 QuantityValue
- ~ 90 string
- ~ 50 float
- ~ 30 integer

uses of other types

```yaml
file_size_bytes:
  range: bytes

has_numeric_value:
  range: decimal

latitude:
  range: decimal_degree

longitude:
  range: decimal_degree

ph:
  range: double

surf_moisture_ph:
  range: double

typ_occup_density:
  range: double

external_database_identifiers:
  range: external_identifier

language:
  range: language_code

has_unit:
  range: unit
```
