### ISSUE TITLE
Move activity and data object generation to automation scripts

### ISSUE THREAD

**Issue by scanon** [microbiomedata/issues#59]
Currently the workflows are responsible for generating the activity and data object JSON.  The automation scripts then ingest these, munge them, and post them.  This has several down sides such as having to modify every workflow if some changes are made in the schema or how IDs are generated.  It would work better if this was moved into the automation side and the workflows would simply pass back things in the output block.  I have a proposed model for how this could be managed in a configuration so it would be easy to maintain.

One reason this is becoming important is we are starting to have issues with how we currently generate the data object IDs (using an MD5 as the ID).  Changing this to a different method will require more changes to the WDL.  So this seems a good time to fix things.

**Comment by scanon** [comment]
Here is my straw man concept....

The activity and objects would be specified in the same place we are using for the specifications used in the automation.  So in YAML form (which we may do some other way) things might look like this for RQC...

```
- Name: Reads QC
    Enabled: True
    Git_repo: https://github.com/microbiomedata/ReadsQC
    Version: b1.0.6
    WDL: rqcfilter.wdl
    Activity: read_qc_analysis_activity_set
    Predecessor: Sequencing
    Input_prefix: nmdc_rqcfilter
    ID_type: mgrqc
    Inputs:
      input_files: do:Metagenome Raw Reads
    Activity:
      name: "Read QC Activity for {id}"
      input_read_bases: "{outputs.input_read_bases}"
      output_read_count: "{outputs.input_read_bases}"
      output_read_bases: "{outputs.input_read_bases}"
      input_read_count: "{outputs.input_read_bases}"
      type: nmdc:ReadQCAnalysisActivity
    Additional Metadata: filter_stats_json
    Outputs:
      - output: filtered_final
        name: Reads QC result fastq (clean data)
        data_object_type: Filtered Sequencing Reads
        description: "Reads QC for {id}"
      - output: filtered_stats2_final
        name: Reads QC result fastq (clean data)
        data_object_type: Filtered Sequencing Reads
        description: "Reads QC for {id}"
      - output: filtered_stats_final
        name: Reads QC summary statistics
        data_object_type: QC Statistics
        description: "Reads QC summary for {id}"
```

The Activity block specifies additional parameters and ones that can't be auto-populated.  Likewise the Outputs block specifies the list of outputs.  Many of the attributes can be auto-populated (e.g. md5, size, URL, etc).

This also reduces information we have to hand off to the workflow since it can be tracked and populated by the automation scripts.
