### ISSUE TITLE
Slot descriptions and fields standardization

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#705]
As part of metabolink2, @anastasiyaprymolenna , @brynnz22 , & @kheal make some new classes and slots or did some re-organizing. This issue is looking at these changes and determining if there's a standardized term that should be used

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/pull/169

**Comment by kheal** [comment]
Yes, that is a direct mapping.  Yes, please fix that typo!  Good catch

**Comment by mslarae13** [comment]
@kheal another one!

```
mass_analyzers:
    range: MassAnalyzerEnum
    description: which kind of mass analyzer(s) used during the spectra collection.
    multivalued: true
```

Looks like https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1000443 

Confirm?

**Comment by kheal** [comment]
Yes, another direct mapping.  You are a much better ontology detective than I am.

**Comment by mslarae13** [comment]
```
resolution_categories:
    range: ResolutionCategoryEnum
    description: whether mass spectra are collected at higher than unit resolution
    multivalued: true
```

This description reads weird to me... the enum has high & low where you can enter values. 

Whether mass spectra sounds like a yes or no? 

Is this meant to be 

"[detector resolution: The resolving power of the detector to detect the smallest difference between two ions so that the valley between them is a specified fraction of the peak height.](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1000028) "

Or 

"[mass resolution: Smallest mass difference between two equal magnitude peaks so that the valley between them is a specified fraction of the peak height.](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1000011)"

Or neither?
