### ISSUE TITLE
env_ triad fields no longer valid or allow for regex string validation

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#718]
Data Harmonizer was updated to required enum fields be from the permissible values and removed the string match with the regular expression validation

NMDC has relied on the string match for previous submissions and validating fields that might not be in our enum but are still valid submissions.

Example, NEON has temperate broadleaf forest biome [ENVO:01000202] for env_broad which is valid and was matched / added to ENVO for NEON. However it wasn't included in the enum PV list as it's new & we haven't updated. This should validate.

We want data harmonizer & the submission portal to validate when the provided information is formatted correctly (regex string match) but still provide the enum PVs in a drop down.

Affected submissions include NEON plate 5, Blanchard, MONet plate 3

**Comment by pkalita-lbl** [comment]
Currently there is a line in the modifications TSV file that overrides the `range` of `env_broad_scale` to be `EnvBroadScaleSoilEnum`: https://github.com/microbiomedata/submission-schema/blob/f9a1f912d77c76a4818d15bf248a6c1682b649b9/sheets_and_friends/tsv_in/modifications_long.tsv?plain=1#L99

In the LinkML YAML file that pops out at the end of the process you get, as you'd expect:

```yaml
      env_broad_scale:
        name: env_broad_scale
        description: 'In this field, report which major environmental system your sample or specimen came from. The systems identified should have a coarse spatial grain, to provide the general environmental context of where the sampling was done (e.g. were you in the desert or a rainforest?). We recommend using subclasses of ENVO''s biome class: http://purl.obolibrary.org/obo/ENVO_00000428. Format (one term): termLabel [termID], Format (multiple terms): termLabel [termID]|termLabel [termID]|termLabel [termID]. Example: Annotating a water sample from the photic zone in middle of the Atlantic Ocean, consider: oceanic epipelagic zone biome [ENVO:01000033]. Example: Annotating a sample from the Amazon rainforest consider: tropical moist broadleaf forest biome [ENVO:01000228]. If needed, request new terms on the ENVO tracker, identified here: http://www.obofoundry.org/ontology/envo.html'
        title: broad-scale environmental context
        notes:
          - range changed to enumeration late in makefile, so this is modified (but "sample ID" anyway)
        from_schema: https://w3id.org/nmdc/nmdc
        rank: 6
        is_a: environment field
        string_serialization: '{termLabel} {[termID]}'
        slot_uri: MIXS:0000012
        multivalued: false
        owner: Biosample
        domain_of:
          - Biosample
        slot_group: sample_id_section
        range: EnvBroadScaleSoilEnum
        required: true
        pattern: ^\S+.*\S+ \[[a-zA-Z]{2,}:\d+\]$
```

As such, DataHarmonizer is doing the correct LinkML thing by not allowing an arbitrary string (even if it follows the `pattern`) in that slot. So what what we really want is a [range union](https://linkml.io/linkml/schemas/advanced.html#unions-as-ranges):

```diff
      env_broad_scale:
        name: env_broad_scale
        description: 'In this field, report which major environmental system your sample or specimen came from. The systems identified should have a coarse spatial grain, to provide the general environmental context of where the sampling was done (e.g. were you in the desert or a rainforest?). We recommend using subclasses of ENVO''s biome class: http://purl.obolibrary.org/obo/ENVO_00000428. Format (one term): termLabel [termID], Format (multiple terms): termLabel [termID]|termLabel [termID]|termLabel [termID]. Example: Annotating a water sample from the photic zone in middle of the Atlantic Ocean, consider: oceanic epipelagic zone biome [ENVO:01000033]. Example: Annotating a sample from the Amazon rainforest consider: tropical moist broadleaf forest biome [ENVO:01000228]. If needed, request new terms on the ENVO tracker, identified here: http://www.obofoundry.org/ontology/envo.html'
        title: broad-scale environmental context
        notes:
          - range changed to enumeration late in makefile, so this is modified (but "sample ID" anyway)
        from_schema: https://w3id.org/nmdc/nmdc
        rank: 6
        is_a: environment field
        string_serialization: '{termLabel} {[termID]}'
        slot_uri: MIXS:0000012
        multivalued: false
        owner: Biosample
        domain_of:
          - Biosample
        slot_group: sample_id_section
-        range: EnvBroadScaleSoilEnum
+        any_of:
+          - range: EnvBroadScaleSoilEnum
+          - range: string
        required: true
        pattern: ^\S+.*\S+ \[[a-zA-Z]{2,}:\d+\]$
```

The thing that actually process that modifications TSV file is https://github.com/microbiomedata/sheets_and_friends. I don't believe there is currently any way of expressing the desired `any_of` construct in the TSV file in a way that `sheets_and_friends` would understand. So the steps here will be:

1. Update `sheets_and_friends` to include a mechanism whereby the range union can be expressed in the TSV file
2. Use that new feature in `submission-schema` on the `env_broad_scale`, `env_local_scale`, and `env_medium` slots
