### ISSUE TITLE
NCBI prefix for `host_taxid` NCBI:txid15368 needs short term definition and long term replacement

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#893]
This may be a duplicate but I haven't found it yet

```YAML
  host_taxid:
    has_raw_value: Brachypodium distachyon [NCBI:txid15368]
    term:
      id: NCBI:txid15368
      name: Brachypodium distachyon
      type: nmdc:OntologyClass
    type: nmdc:ControlledIdentifiedTermValue
```

Problems: 
- The schema doesn't have a definition for the `NCBI` prefix. This is a case in which a prefix was introduced in the Submission Portal. That's a vulnerability! Maybe we should put more pattern constraints on slots that are expected to capture a CURIe (with or without other content like a label)
- `NCBI` isn't a great prefix, unless all CURIes that use that prefix can be resolved to the same base URL. In this case, it would appear that NCBI:txid15368 is meant to resolve to https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=15368.
- The local id in this case, txid15368, contains information about the source system, which should entirely be captured in the prefix.

I acknowledge that the NCBI:txid... style has been promoted by both NCBI and MIxS, and that resolving these terms to the NCBI pages is preferable to resolving them to the ontological representation of NCBI Taxonomy, as illustrated in https://bioregistry.io/registry/ncbitaxon

Temporary solution:

```yaml
NCBI: "http://example.com/ncbitaxon/"
```

in src/schema/nmdc.yaml
